version: 2
jobs:
  build:
    working_directory: ~/graphpaper
    docker:
      - image: circleci/node:7.10.0
    environment:
      - NODE_ENV: development      
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install modules
          command: yarn install --verbose
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
