version: 2
jobs:
  build:
    working_directory: ~/repo
    
    docker:
      - image: circleci/node:10.0.0
    environment:
      - NODE_ENV: development      
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test

      - run: 
          name: Installing rollup
          command: sudo npm install --global rollup
      
      - run: 
          name: Building /dist files
          command: npm run build

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - deploy:
          name: Updating version num and publishing
          command: |
            if [[ "${CIRCLE_TAG}" =~ v[0-9]+(\.[0-9]+)* ]]; then
              npm --no-git-tag-version version ${CIRCLE_TAG:1}
              npm publish
            fi

      - store_artifacts:
          path: ~/repo/dist          

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
