version: 2
jobs:
  build:
    working_directory: ~/graphpaper
    docker:
      - image: circleci/node:10.0.0
    environment:
      - NODE_ENV: development      
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install modules
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test

      - run: 
          name: Installing rollup
          command: sudo npm install --global rollup
      
      - run: 
          name: Creating /dist files with rollup
          command: rollup -c

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
